<a href="https://colab.research.google.com/github/cisirtraining/summerschool/blob/master/Day1_Intro_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Introduction to Numerical Computing with Numpy (20 minutes)**

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=1Bv6N-OnGfesnGW-CsigdA0KNeoE05xa9' />
</center>
</figure>


[Source](https://numpy.org/)


###**Mount Google Drive**



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#### **Normal List/Array Operation Without Numpy**

Python list does not supports direct calculation (addition, substraction, multiplication, division etc.)

In [ ]:
a = [1, 2, 3, 4, 5]
b = [10, 11, 12, 13, 14]

print(a + b)
print('\n{} is not equal to 11, 13, 15, 17, 19'.format(a+b)) 


[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14] is not equal to 11, 13, 15, 17, 19


In [ ]:
# for loop approach

result = []
for x, y in zip(a,b):
  result.append(x + y)

print(result)


[11, 13, 15, 17, 19]


In [ ]:
# list comprehension approach
result = [x+y for (x,y) in zip(a,b)]

print(result)

[11, 13, 15, 17, 19]


#### **Numpy Style**

In [ ]:
import numpy as np
print('numpy version:',np.__version__)

a = np.array([1,2,3,4,5])
print('a:',a)
print('type of a:',type(a))

numpy version: 1.18.5
a: [1 2 3 4 5]
type of a: <class 'numpy.ndarray'>


In [ ]:
a.dtype

dtype('int64')

In [ ]:
f = np.array([1.2,2.3,4.5,5.6, 7.2])
f.dtype

dtype('float64')

In [ ]:
print('a = ',a)
a[0] = 10
print('a = ',a)
a[2] = 13.6
print('a =', a)

a =  [1 2 3 4 5]
a =  [10  2  3  4  5]
a = [10  2 13  4  5]


In [ ]:
# return tuple of elements along each dimension @ equivalent to size (MATLAB)
a.shape

(5,)

In [ ]:
add = a + f
multip = a * f
divis = a / f
pwr = f**a

print('a:', a)
print('f:',f)
print('multiply:', multip)
print ('division:',divis)
print ('power:',pwr)

a: [10  2 13  4  5]
f: [1.2 2.3 4.5 5.6 7.2]
multiply: [12.   4.6 58.5 22.4 36. ]
division: [8.33333333 0.86956522 2.88888889 0.71428571 0.69444444]
power: [6.19173642e+00 5.29000000e+00 3.10286356e+08 9.83449600e+02
 1.93491763e+04]


### **Universal Functions (ufuncs)**
[More Info](https://numpy.org/doc/stable/reference/ufuncs.html)

In [ ]:
# Universal function (ufuncs) 
print('a =',a)
print('f =',f)
print('sin(f) =', np.sin(f))
print('cos(f) =',np.cos(f))
print('a + f =',np.add(a,f))
print('a % f =',np.mod(a,f))
print('a == f =',np.equal(a,f))
print('f > a =',np.greater(f,a))

a = [10  2 13  4  5]
f = [1.2 2.3 4.5 5.6 7.2]
sin(f) = [ 0.93203909  0.74570521 -0.97753012 -0.63126664  0.79366786]
cos(f) = [ 0.36235775 -0.66627602 -0.2107958   0.77556588  0.60835131]
a + f = [11.2  4.3 17.5  9.6 12.2]
a % f = [0.4 2.  4.  4.  5. ]
a == f = [False False False False False]
f > a = [False  True False  True  True]


### **Multi-Dimensional Array (Indexing @ Slicing)**

In [ ]:
# Multi-Dimensional Array

b = np.array([[0, 1, 3, 5, 7], [10, 11, 12, 13, 14], [20, 22, 24, 25, 27]])
print(b)
print('shape:',b.shape)
print('size:',b.size)

[[ 0  1  3  5  7]
 [10 11 12 13 14]
 [20 22 24 25 27]]
shape: (3, 5)
size: 15


In [ ]:
# var[lower:upper:step] @ [lower:upper:step)

a = np.array([1,5,7,9,12])
print('a = ',a)
print('\na[1:3] =',a[1:3])
print('a[:3] =',a[:3])
print('a[-2:] =',a[-2:])

# select every other element
print('a[::2] = ',a[::2])

# negative indexing
print('a[1:-2] =',a[1:-2])

a =  [ 1  5  7  9 12]

a[1:3] = [5 7]
a[:3] = [1 5 7]
a[-2:] = [ 9 12]
a[::2] =  [ 1  7 12]
a[1:-2] = [5 7]


<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=1iHlMBNgSAeaojqx-fsd7blK2qV0DcoxT' />
</center>
</figure>



In [ ]:
b = np.array([[0, 1, 3, 5, 7], [10, 11, 12, 13, 14], [20, 22, 24, 25, 27]])

print('b =',b)
print('\nb[0,:-2] =',b[0,:-2])
print('b[:,2] =',b[:,2])
print('b[2:,2:] = ',b[2:,2:])
print('b[::2,::2] = ',b[::2,::2])


b = [[ 0  1  3  5  7]
 [10 11 12 13 14]
 [20 22 24 25 27]]

b[0,:-2] = [0 1 3]
b[:,2] = [ 3 12 24]
b[2:,2:] =  [[24 25 27]]
b[::2,::2] =  [[ 0  3  7]
 [20 24 27]]


### **Practice Questions**

 <figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=1ez66CZ6nYUIbPE7GZ7a9HclgjaDTl2P_' />
</center>
</figure>



1.   Select the red colored numbers
2.   Select the yellow colored numbers
3.   Select the blue colored numbers




In [ ]:
c = np.arange(25).reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# solution for red color selections


In [ ]:
# solution for yellow selections


In [ ]:
# solution for blue selections


#### **Memory Buffer in Numpy**

In [ ]:
a = np.array([1,2,3,4,5])
b = a[:2]    # new array object but not new number (memory buffer shared!)
print('a:',a)
print('b:',b)


a: [1 2 3 4 5]
b: [1 2]


In [ ]:
b[0] = -5
print('b:',b)

# check what happen to a?
print('a:',a)
print('what kind of sorcery is this? omg!')

b: [-5  2]
a: [-5  2  3  4  5]
what kind of sorcery is this? omg!


In [ ]:
# Solution
a = np.array([1,2,3,4,5])
b = a.copy()
b[0] = -5

print('b:',b)
print('a:',a)


b: [-5  2  3  4  5]
a: [1 2 3 4 5]


#### **Fancy Indexing**

In [ ]:
# indexing with POSITION @ (COORDINATE)

a = np.arange(0,50,5)

idx = [1,2,-3]
y = a[idx]
print('a:',a)
print('y:',y)

a: [ 0  5 10 15 20 25 30 35 40 45]
y: [ 5 10 35]


In [ ]:
# indexing with BOOLEANS
mask = np.array([0,1,1,0,0,1,1,1,0,0], dtype= bool)

y = a[mask]
print('a:',a)
print('y:',y)

a: [ 0  5 10 15 20 25 30 35 40 45]
y: [ 5 10 25 30 35]



<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=19qG0v2qCYw7NwB7ihqKvHjSh9JORQTnT' />
</center>
</figure>





In [ ]:
d = np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
d

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
# orange colored selection
print('orange:',d[[0,1,2,3,4],[1,2,3,4,5]])

# blue colored selection - slices not possible due to different step size (2 to 3)
print('blue:', d[3:,[0,2,5]])

# red colored selection
idx = np.array([1,0,1,0,0,1], dtype=bool)
print('red:', d[idx,2])

orange: [ 1 12 23 34 45]
blue: [[30 32 35]
 [40 42 45]
 [50 52 55]]
red: [ 2 22 52]


### **Practice Question**


1.   Extract all numbers divisible by 3 using boolean mask (hint: use modulo (%))



In [ ]:
v = np.arange(25).reshape(5,5)
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# solution

### **Visualizing ND-Arrays**

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=1JewIXqZXrx4FPc7UJenBdiVxHTYbRVkL' width="450" height="350" />
</center>
</figure>





### **Computations with Arrays:**

1.   Operation between mutiple array objects are first checked for proper shape match
2.   Mathematic operators (+ - * /,exp,log...) apply element by element, on the values
3.   Reduction operation (mean, stdm sum, prod, skew) apply to the whole array, unless an axis is specified
4.   Missing values propagate unless explicitly ignored (nanmean, nansum, etc.)



### **Array Broadcasting**

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=1XXrB6VQIbqjuLPofaR03NhjOOOBtJ7U7' width="550" height="350" />
</center>
</figure>

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=1xAn52qy4CwB2R75ybFzXwA8VXrDTgafq' width="250" height="350" />
</center>
</figure>


In [ ]:
# Sum method

p = np.array([[1,2,3],[4,5,6]])

print('p:',p)
print('\nshape of p:', p.shape)
# .sum() default to adding up all values in an array, return single value
print('\nsum of p:',p.sum())

# supply keyword axis to sum along intended axis
# axis that we specified is the one that go away

print('sum of p (column-wise)', p.sum(axis=0))
print('sum of p (row-wise)', p.sum(axis=1))

p: [[1 2 3]
 [4 5 6]]

shape of p: (2, 3)

sum of p: 21
sum of p (column-wise) [5 7 9]
sum of p (row-wise) [ 6 15]


In [ ]:
 # argmax/argmin - return location index

 r = np.array([4,7,2,12,35,67,101,54,23])
 
 print('r:',r)
 print('max:',r.max())
 print('location max:',r.argmax())
 print('min:',r.min())
 print('location min:',r.argmin())

r: [  4   7   2  12  35  67 101  54  23]
max: 101
location max: 6
min: 2
location min: 2


In [ ]:
# argmax and argmin only return the first index encountered

q = np.array([4,7,2,12,35,67,101,101,2,23])

print('q:',q)
print('max:',q.max())
print('location max:',q.argmax())
print('min:',q.min())
print('location min:',q.argmin())

q: [  4   7   2  12  35  67 101 101   2  23]
max: 101
location max: 6
min: 2
location min: 2


In [ ]:
# solution
print('location max:', np.where(q == q.max()))
print('location min:', np.where(q == q.max()))

location max: (array([6, 7]),)
location min: (array([6, 7]),)


In [ ]:
# create random values of half-open interval [0.0,1.0)

print('1D:',np.random.random(5))
print('\n2D:',np.random.random((3,3)))

1D: [0.74573014 0.15171706 0.77250465 0.76131285 0.21534495]

2D: [[0.47120351 0.47534834 0.61967507]
 [0.77187613 0.54519967 0.97132757]
 [0.49056011 0.73927013 0.1132405 ]]


In [ ]:
# create random interger values np.random.randint(min, max, size)

print('2D:', np.random.randint(0,40,(5,5)))
print('\n1D:', np.random.randint(-100, 80, 10).astype("float"))

2D: [[ 9  4  8 19 21]
 [ 2 20 15  1 11]
 [ 2 25 17 31  6]
 [19 29 11 20 23]
 [ 2 29 12  8 23]]

1D: [-52. -61.  63. -17. -76. -12. -31. -41. -66. -88.]


In [ ]:
w = np.random.randint(0,40,(5,5)).astype('float')

print('w:',w)
print('\n',np.where(w > 25))

# np.where(condition,x, y) if condition satisfied return x else return y:

print('\n',np.where(w > 25, 1, 10*w))

print('\n',np.where(w < 25, -1, w))

w: [[10. 25. 16. 32. 23.]
 [ 3. 29. 16.  4. 31.]
 [23. 23. 19. 29. 13.]
 [15. 32. 30. 18. 31.]
 [10. 15.  9. 27. 16.]]

 (array([0, 1, 1, 2, 3, 3, 3, 4]), array([3, 1, 4, 3, 1, 2, 4, 3]))

 [[100. 250. 160.   1. 230.]
 [ 30.   1. 160.  40.   1.]
 [230. 230. 190.   1. 130.]
 [150.   1.   1. 180.   1.]
 [100. 150.  90.   1. 160.]]

 [[-1. 25. -1. 32. -1.]
 [-1. 29. -1. -1. 31.]
 [-1. -1. -1. 29. -1.]
 [-1. 32. 30. -1. 31.]
 [-1. -1. -1. 27. -1.]]


In [ ]:
s = np.random.randint(0,20,(5,6)).astype('float')
s

array([[19.,  4., 14., 12., 15.,  7.],
       [19., 17.,  3.,  2.,  4., 19.],
       [ 9.,  6., 18., 17., 17., 14.],
       [ 4., 18., 12.,  0., 17.,  3.],
       [ 1., 19., 10., 15.,  1.,  4.]])

In [ ]:
# reshape s from 5x6 to 2x5x3
print(s.reshape(2,5,3))

[[[19.  4. 14.]
  [12. 15.  7.]
  [19. 17.  3.]
  [ 2.  4. 19.]
  [ 9.  6. 18.]]

 [[17. 17. 14.]
  [ 4. 18. 12.]
  [ 0. 17.  3.]
  [ 1. 19. 10.]
  [15.  1.  4.]]]


In [ ]:
# create zeros matrix
print('zeros:\n',np.zeros((3,5)))

# create ones matrix
print('\nones:\n',np.ones((7,5)))

# create full matrix
print('\nfull:\n', np.full((4,5),-999))

# create identity matrix
print('\nidentity:\n',np.eye(5))

print('\nidentity shitfted:\n',np.eye(5,4,k=1))

zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

full:
 [[-999 -999 -999 -999 -999]
 [-999 -999 -999 -999 -999]
 [-999 -999 -999 -999 -999]
 [-999 -999 -999 -999 -999]]

identity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

identity shitfted:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# joining multiple arrays to create single array
x = np.array([1,2,3,4]) 
y = np.array([5,6,7,8])
z = np.array([9,10,11,12])

# method 1: concat axis=0
xyz = np.concatenate((x,y,z))
print(xyz)

# method 2: horizontal stack
abc = np.hstack((x,y,z))
print(abc)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
